### PR TITLE
Initial markdown clean-up

### PR DESCRIPTION
**Pull request by aweinert-MIT**
**No technical content was changed or added**

- Create LICENSE file instead of linking to external license
- Mlint formatting changes
- Added default READMEs for each directory
- Changed image links from hard coded to relative
- Removed whitespace from tutorial markdown filenames

### CODE REVIEW

**Comment by jeffliu-LL** [comment]
The Sagemaker tutorial isn't complete. Do we want to remove it from this version until it's completed? I think it would cause more confusion to have a half-finished tutorial in it.

**Comment by aweinert-MIT** [comment]
I'm okay with removing the sagemaker tutorial. We can refer to the branch history to use a starting point in the future

**Comment by jeffliu-LL** [comment]
Would you mind making that change and then incorporating it into the PR? I'm in a meeting until 5.

**Comment by aweinert-MIT** [comment]
I removed the sagemaker tutorial markdown file and the reference to it in the root README

**Pull request merged**
